delete from changeattributestates;
delete from changereasons;
delete from changes;
delete from changedetails;
delete from changetablenames;
delete from abbreviation;
delete from aspiration;
delete from basevehicle;
delete from bedconfig;
delete from bedlength;
delete from bedtype;
delete from bodynumdoors;
delete from bodystyleconfig;
delete from bodytype;
delete from brakeabs;
delete from brakeconfig;
delete from brakesystem;
delete from braketype;
delete from cylinderheadtype;
delete from drivetype;
delete from eleccontrolled;
delete from enginebase;
delete from engineconfig;
delete from enginedesignation;
delete from engineversion;
delete from enginevin;
delete from fueldeliveryconfig;
delete from fueldeliverysubtype;
delete from fueldeliverytype;
delete from fuelsystemcontroltype;
delete from fuelsystemdesign;
delete from fueltype;
delete from ignitionsystemtype;
delete from make;
delete from mfrbodycode;
delete from mfr;
delete from model;
delete from region;
delete from springtypeconfig;
delete from springtype;
delete from steeringconfig;
delete from steeringsystem;
delete from steeringtype;
delete from submodel;
delete from transmissionbase;
delete from transmissioncontroltype;
delete from transmissionmfrcode;
delete from transmissionnumspeeds;
delete from transmission;
delete from transmissiontype;
delete from valves;
delete from vehicletobedconfig;
delete from vehicletobodystyleconfig;
delete from vehicletobrakeconfig;
delete from vehicletodrivetype;
delete from vehicletoengineconfig;
delete from vehicletomfrbodycode;
delete from vehicletospringtypeconfig;
delete from vehicletosteeringconfig;
delete from vehicletotransmission;
delete from vehicletowheelbase;
delete from vehicle;
delete from vehicletype;
delete from version;
delete from wheelbase;
delete from year;
LOAD DATA LOCAL INFILE './changedetails' INTO TABLE changedetails FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './changetablenames' INTO TABLE changetablenames FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './changes' INTO TABLE changes FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './changereasons' INTO TABLE changereasons FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './changeattributestates' INTO TABLE changeattributestates FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './abbreviation' INTO TABLE abbreviation FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './aspiration' INTO TABLE aspiration FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './basevehicle' INTO TABLE basevehicle FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bedconfig' INTO TABLE bedconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bedlength' INTO TABLE bedlength FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bedtype' INTO TABLE bedtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bodynumdoors' INTO TABLE bodynumdoors FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bodystyleconfig' INTO TABLE bodystyleconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './bodytype' INTO TABLE bodytype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './brakeabs' INTO TABLE brakeabs FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './brakeconfig' INTO TABLE brakeconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './brakesystem' INTO TABLE brakesystem FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './braketype' INTO TABLE braketype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './cylinderheadtype' INTO TABLE cylinderheadtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './drivetype' INTO TABLE drivetype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './eleccontrolled' INTO TABLE eleccontrolled FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './enginebase' INTO TABLE enginebase FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './engineconfig' INTO TABLE engineconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './enginedesignation' INTO TABLE enginedesignation FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './engineversion' INTO TABLE engineversion FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './enginevin' INTO TABLE enginevin FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fueldeliveryconfig' INTO TABLE fueldeliveryconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fueldeliverysubtype' INTO TABLE fueldeliverysubtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fueldeliverytype' INTO TABLE fueldeliverytype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fuelsystemcontroltype' INTO TABLE fuelsystemcontroltype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fuelsystemdesign' INTO TABLE fuelsystemdesign FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './fueltype' INTO TABLE fueltype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './ignitionsystemtype' INTO TABLE ignitionsystemtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './make' INTO TABLE make FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mfrbodycode' INTO TABLE mfrbodycode FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './mfr' INTO TABLE mfr FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './model' INTO TABLE model FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './region' INTO TABLE region FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './springtypeconfig' INTO TABLE springtypeconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './springtype' INTO TABLE springtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './steeringconfig' INTO TABLE steeringconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './steeringsystem' INTO TABLE steeringsystem FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './steeringtype' INTO TABLE steeringtype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './submodel' INTO TABLE submodel FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmissionbase' INTO TABLE transmissionbase FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmissioncontroltype' INTO TABLE transmissioncontroltype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmissionmfrcode' INTO TABLE transmissionmfrcode FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmissionnumspeeds' INTO TABLE transmissionnumspeeds FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmission' INTO TABLE transmission FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './transmissiontype' INTO TABLE transmissiontype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './valves' INTO TABLE valves FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletobedconfig' INTO TABLE vehicletobedconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletobodystyleconfig' INTO TABLE vehicletobodystyleconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletobrakeconfig' INTO TABLE vehicletobrakeconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletodrivetype' INTO TABLE vehicletodrivetype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletoengineconfig' INTO TABLE vehicletoengineconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletomfrbodycode' INTO TABLE vehicletomfrbodycode FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletospringtypeconfig' INTO TABLE vehicletospringtypeconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletosteeringconfig' INTO TABLE vehicletosteeringconfig FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletotransmission' INTO TABLE vehicletotransmission FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletowheelbase' INTO TABLE vehicletowheelbase FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicle' INTO TABLE vehicle FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './vehicletype' INTO TABLE vehicletype FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './version' INTO TABLE version FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (@versiondate) SET versiondate=str_to_date(@versiondate,'%m/%d/%Y');
LOAD DATA LOCAL INFILE './wheelbase' INTO TABLE wheelbase FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE './year' INTO TABLE year FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
